### PR TITLE
Updating the web-recalculate data model

### PR DESCRIPTION
**Pull request by bernardosrulzon**
This PR does two simple things:

- Avoids creating an unnecessary `snowplow_intermediary.events_enriched` table. It saved ~25% Redshift disk space for us!
- Adds a fairly simple `cookie_id_to_user_id_map` query to map `domain_userids` to `user_ids`

Feedback appreciated!

### CODE REVIEW

**Comment by alexanderdean** [comment]
Thanks for contributing! Assigning to @bogaert to review...

**Comment by bogaert** [comment]
Hi @bernardosrulzon. Those changes look good to me (`web-recalculate` hasn't been updated in a while). It'd be great if you could:

- rebase of `master` to resolve the merge conflicts
- rebase the commits to map onto the following 2 tickets:

https://github.com/snowplow/snowplow/issues/2274
https://github.com/snowplow/snowplow/issues/2275

The changes will then be included in our next release.

Thanks for contributing!

**Comment by bernardosrulzon** [comment]
@bogaert Done! I've reopened as #2276 as I made a big mess out of the commits :disappointed:

**Comment by bogaert** [comment]
Thanks @bernardosrulzon!

**Comment by bogaert** [comment]
Hi @bernardosrulzon. These commits were included in R75: http://snowplowanalytics.com/blog/2016/01/02/snowplow-r75-long-legged-buzzard-released/#datamodel

**Comment by bernardosrulzon** [comment]
@bogaert Awesome, thanks!

**Pull request closed without merging**
