### PR TITLE
Remove duplicate h that broke the url

### PR DESCRIPTION
**Pull request by dosire**

### CODE REVIEW

**Comment by snowplowcla** [comment]
Thanks for your pull request. Is this your first contribution to a Snowplow open source project? Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).

:memo: Please visit https://github.com/snowplow/snowplow/wiki/CLA to learn more and sign.

Once you've signed, please reply here (e.g. I signed it!) and we'll verify. Thanks.

**Comment by dosire** [comment]
I signed it!

Individual Contributor License Agreement v1.0
Thank you, your signature on Snowplow's Individual Contributor License Agreement has been recorded.

**Comment by snowplowcla** [comment]
Confirmed! @dosire has signed the Contributor License Agreement. Thanks so much.

**Comment by benjben** [comment]
Hi @dosire , thank you for the contribution !

Could you please create the issue `Scala Stream Collector: remove duplicate h in README` and rename your commit `Scala Stream Collector: remove duplicate h in README (closes #xxxx)` with the number of the issue to match our [commit hygiene](https://github.com/snowplow/snowplow/blob/master/CONTRIBUTING.md#commit-hygiene) ?

**Comment by benjben** [comment]
Hey @dosire , I'll take care of this and will `cherry-pick` your commit and rename it, thank you!

**Pull request merged**
