### PR TITLE
Update streaming components to latest vn (1.11.86)

### PR DESCRIPTION
**Pull request by acgray**
Also limiting deps to only necessary components to reduce build size

### CODE REVIEW

**Comment by acgray** [comment]
This passes but still uses my private fork of Scalazon with the upgraded SDK version. I've submitted a PR with those changes and I'll update this PR once they get released...

**Comment by snowplowcla** [comment]
@acgray has signed the Software Grant and Corporate Contributor License Agreement.

**Comment by BenFradet** [comment]
@acgray 

Unfortunately, we''re moving away from Scalazon since it doesn't seem to be maintained anymore (cf #3300 and #3341). Moreover, the sdk versions will be updated as part of #3274.

Thanks a lot for your contribution anyway!

**Comment by acgray** [comment]
No worries, that suits me just fine!

**Pull request closed without merging**
