### PR TITLE
Scala Stream Collector: override network_id cookie with nuid query param

### PR DESCRIPTION
**Pull request by christoph-buente**

### CODE REVIEW

**Comment by alexanderdean** [comment]
Thanks, appreciate the rich tests! Assigning to @fblundun to review...

**Comment by christoph-buente** [comment]
@alexanderdean this one is also still assigned to @fblundun.

**Comment by alexanderdean** [comment]
Thanks @christoph-buente, did you make the updates following @kazjote's feedback?

**Comment by christoph-buente** [comment]
Actually i didn't, because it is referring code, that i did not touch at all. So i thought, this should not be part of this PR.

**Comment by alexanderdean** [comment]
Makes sense!

**Comment by christoph-buente** [comment]
I applied some comments now, that fix specs and provide real value.

**Comment by jbeemster** [comment]
Closing as duplicate of https://github.com/snowplow/snowplow/issues/2512

**Pull request closed without merging**
