### PR TITLE
Release/r82

### PR DESCRIPTION
**Pull request by chuwy**
### New features
 
+ SQL Query Enrichments https://github.com/snowplow/snowplow/issues/2321

### Version bumps

+ Scala Common Enrichment  https://github.com/snowplow/snowplow/issues/2715
+ Scala Hadoop Enrichment https://github.com/snowplow/snowplow/issues/2716  https://github.com/snowplow/snowplow/issues/2717

### CODE REVIEW

**Comment by alexanderdean** [comment]
Thanks @chuwy ! This is looking great. Excited to get this into test with @ihortom. I have assigned some other R82 tickets to you - if you could apply them into this branch that would be great.

I've also asked @jbeemster to merge in his work on the Iglu webhook adapter into your branch as soon as he is able...

**Comment by alexanderdean** [comment]
Hey @chuwy, @jbeemster, this is coming together! A few pieces of feedback:

1. By the time you read this, this version will be in test, so please bump everything to -M2, -rc2 etc
2. For consistency we should upgrade Scala Hadoop Shred's Scala Common Enrich dependency
3. @jbeemster please make the change to the qsBody per my comments yesterday
4. @chuwy please rebase R82 onto R81 (which went out today)

Thanks both! Exciting...

**Comment by chuwy** [comment]
Branch has been force-pushed with test in SHE enabled and fixed `com.amazon.aws.lambda/s3_notification_event`. Please make sure you have last changes.

**Comment by chuwy** [comment]
Hey @alexanderdean! @ihortom discovered a bug related to MySQL. Could you please publish rc2?

**Comment by alexanderdean** [comment]
Hey @jbeemster - would you mind bumping Stream Enrich to rc2 making use of Common Enrich M3? I can build CE M3 now...

**Comment by jbeemster** [comment]
No worries, let me know when M3 is live and I will bump and build the Kinesis artifacts.

**Comment by alexanderdean** [comment]
Thanks @jbeemster !

**Comment by alexanderdean** [comment]
Closing this PR as we are going to rebase all this onto a new branch...

**Pull request closed without merging**
