### PR TITLE
Updating sql-runner scripts

### PR DESCRIPTION
**Pull request by bernardosrulzon**
This simple PR:
1. Updates the dedupication script to work with atomic.events 0.7.0
2. Fixes path names on the web-recalculate playbook

### CODE REVIEW

**Comment by alexanderdean** [comment]
Thanks! @bernardosrulzon - have you signed our CLA? https://github.com/snowplow/snowplow/wiki/CLA

**Comment by bernardosrulzon** [comment]
Done!

**Comment by alexanderdean** [comment]
Confirmed! Thanks so much.

**Comment by bogaert** [comment]
Hi @bernardosrulzon. Thanks a lot for this PR. I have, however, closed it because these SQL queries will replaced with brand new ones in R72.

**Comment by bernardosrulzon** [comment]
No problem, thanks!

**Pull request closed without merging**
