### PR TITLE
Scala Stream Collector: configurable cookie path

### PR DESCRIPTION
**Pull request by christoph-buente**
Hardwire the cookie path to / to make sure it also is valid for nested urls like click track.

This solves #2524

### CODE REVIEW

**Comment by alexanderdean** [comment]
Thanks! Scheduling

**Comment by alexanderdean** [comment]
Thanks so much @christoph-buente - scheduling!

**Comment by christoph-buente** [comment]
Did this PR ever make it into upstream? I cannot see it in the current master.

**Comment by alexanderdean** [comment]
Bringing forwards (R82 is in test already)

**Comment by alexanderdean** [comment]
Thanks @christoph-buente - this did get somewhat forgotten. Have given it a concrete release now.

**Pull request closed without merging**
