### PR TITLE
Allow to retry failed jobs and to kill clusters that don't terminate

### PR DESCRIPTION
**Pull request by danisola**
This PR enables `emr-etl-runner` to terminate the cluster after a configurable timeout and to rerun an EMR job a configurable number of times.

### CODE REVIEW

**Comment by alexanderdean** [comment]
This is very cool! Thanks for contributing @danisola.

**Comment by danisola** [comment]
Thanks for Snowplow! ;)

**Comment by alexanderdean** [comment]
Hey @danisola . I took another a look at this. Imagine a Snowplow user where:

* Your nightly job takes about 3 hours
* You set the failure threshold to 4 hours to be safe
* You set the job to run at 5am so your analysts have up-to-date data when they get in
* You want to try three times in the case of a bootstrap failure

Here are a couple of scenarios:

Scenario | Old approach  | PR approach
------------ | ------------ | -------------
Bootstrap failure | Job fails to start. Engineer fixes when he wakes up | Job starts on second attempt. Data is ready 10 minutes later than usual |
Failure in shredding process | Job fails 2 hours in. Engineer fixes when he wakes up | Job fails 2 hours in, 3 times in a row. EmrEtlRunner is still running at 10am. Engineer goes into AWS Dashboard and realizes what is going on |

I think rather than attempting blanket restart, we should detect a failure to launch (bootstrap failure) as per this ticket #354 and only retry in this special case.

**Comment by danisola** [comment]
Hi Alex. We did it this way because occasionally (2-3 times a month) we have S3DistCp jobs getting stuck. That's the syslog of the last D3DistCp job that hung:

```
2015-02-19 15:06:55,840 INFO com.amazon.elasticmapreduce.s3distcp.S3DistCp (main): Running with args: [Ljava.lang.String;@471719b6
2015-02-19 15:07:00,511 INFO com.amazon.elasticmapreduce.s3distcp.S3DistCp (main): Using output path 'hdfs:/tmp/0deac8e1-16fe-4756-b3a1-b4a9e77a4c1f/output'
2015-02-19 15:07:00,577 INFO com.amazon.elasticmapreduce.s3distcp.FileInfoListing (main): Opening new file: hdfs:/tmp/0deac8e1-16fe-4756-b3a1-b4a9e77a4c1f/files/1
2015-02-19 15:07:00,736 INFO com.amazon.elasticmapreduce.s3distcp.S3DistCp (main): Created 1 files to copy 18 files 
2015-02-19 15:07:01,242 INFO org.apache.hadoop.mapred.JobClient (main): Default number of map tasks: null
2015-02-19 15:07:01,243 INFO org.apache.hadoop.mapred.JobClient (main): Setting default number of map tasks based on cluster size to : 8
2015-02-19 15:07:01,243 INFO org.apache.hadoop.mapred.JobClient (main): Default number of reduce tasks: 3
2015-02-19 15:07:01,386 INFO org.apache.hadoop.security.ShellBasedUnixGroupsMapping (main): add hadoop to shell userGroupsCache
2015-02-19 15:07:01,391 INFO org.apache.hadoop.mapred.JobClient (main): Setting group to hadoop
2015-02-19 15:07:01,431 INFO org.apache.hadoop.mapred.FileInputFormat (main): Total input paths to process : 1
2015-02-19 15:07:02,661 INFO org.apache.hadoop.mapred.JobClient (main): Running job: job_201502191448_0007
2015-02-19 15:07:03,664 INFO org.apache.hadoop.mapred.JobClient (main):  map 0% reduce 0%
```

In my mind, the old approach and the PR approach aren't that different: in both cases the engineer will have to check what's going on if the data is not present when she/he wakes up.

**Comment by alexanderdean** [comment]
Hey @danisola - thanks, that's helpful background. Next scenario: you have a volume spike one day and the processing time takes you over your threshold, then the job gets killed and you have to start over once you realize what's happened. That puts your processing doubly-behind schedule. Have you had this happen?

**Comment by danisola** [comment]
No, we process our logs hourly and we haven't seen any spikes that make the processing time go over the threshold. In our experience, the processing time is much more dependent on the number of files (that is, days) than on the size of the files.

**Comment by alexanderdean** [comment]
Okay, that makes sense. I've brainstormed it through with Yali and the team. Our verdict:

* The only jobflow failure that we have seen _under which it is always safe & always fruitful to restart a jobflow_ is bootstrap failure. Bootstrap failure can always be unambiguously identified. With any other failure, a human review is needed
* Killing and restarting a job which has taken longer than some expected fixed duration is a very crude mechanism. What we would expect to do instead is send alerts if a job is taking longer than expected. Then a human operator can review the job and identify whether it is a job step hang, a larger-than-usual event volume, a missing schema from Iglu or whatever

Therefore, our plan is to adapt your PR to remove the jobflow-killing aspects and add in the check that a jobflow failure is a bootstrap failure before attempting a restart.

**Comment by alexanderdean** [comment]
Also I wanted to check: have you filed a bug with AWS about the S3DistCp hangs?

**Comment by danisola** [comment]
> Therefore, our plan is to adapt your PR to remove the jobflow-killing aspects and add in the check that a jobflow failure is a bootstrap failure before attempting a restart.

Is fine. We'll keep the change it in our private repo as it's a big time saver for us.

> Have you filed a bug with AWS about the S3DistCp hangs?

We haven't, our experience with AWS is that every time we've complained about transient EMR errors they just tell us to retry the job.

**Comment by alexanderdean** [comment]
Okay great stuff, thanks @danisola !

**Comment by danisola** [comment]
Hey Alex,
Just wanted to comment that we've come across another exception when starting the cluster that you might consider to catch and retry:

```
RestClient::HTTPVersionNotSupported (505 HTTP Version Not Supported):
    /home/ec2-user/snowplow/shared/bundle_emr-etl-runner/ruby/1.9.1/gems/rest-client-1.6.7/lib/restclient/abstract_response.rb:48:in `return!'
    /home/ec2-user/snowplow/shared/bundle_emr-etl-runner/ruby/1.9.1/gems/rest-client-1.6.7/lib/restclient/request.rb:230:in `process_result'
    /home/ec2-user/snowplow/shared/bundle_emr-etl-runner/ruby/1.9.1/gems/rest-client-1.6.7/lib/restclient/request.rb:178:in `block in transmit'
    /home/ec2-user/.rbenv/versions/1.9.3-p547/lib/ruby/1.9.1/net/http.rb:746:in `start'
    /home/ec2-user/snowplow/shared/bundle_emr-etl-runner/ruby/1.9.1/gems/rest-client-1.6.7/lib/restclient/request.rb:172:in `transmit'
    /home/ec2-user/snowplow/shared/bundle_emr-etl-runner/ruby/1.9.1/gems/rest-client-1.6.7/lib/restclient/request.rb:64:in `execute'
    /home/ec2-user/snowplow/shared/bundle_emr-etl-runner/ruby/1.9.1/gems/rest-client-1.6.7/lib/restclient/request.rb:33:in `execute'
    /home/ec2-user/snowplow/shared/bundle_emr-etl-runner/ruby/1.9.1/gems/rest-client-1.6.7/lib/restclient.rb:72:in `post'
    /home/ec2-user/snowplow/shared/bundle_emr-etl-runner/ruby/1.9.1/gems/elasticity-3.0.4/lib/elasticity/aws_request.rb:27:in `submit'
    /home/ec2-user/snowplow/shared/bundle_emr-etl-runner/ruby/1.9.1/gems/elasticity-3.0.4/lib/elasticity/emr.rb:191:in `run_job_flow'
    /home/ec2-user/snowplow/shared/bundle_emr-etl-runner/ruby/1.9.1/gems/elasticity-3.0.4/lib/elasticity/job_flow.rb:131:in `run'
    /home/ec2-user/snowplow/releases/20150226101732/3-enrich/emr-etl-runner/lib/snowplow-emr-etl-runner/emr_job.rb:297:in `run'
    /home/ec2-user/snowplow/shared/bundle_emr-etl-runner/ruby/1.9.1/gems/contracts-0.4/lib/contracts.rb:230:in `call'
    /home/ec2-user/snowplow/shared/bundle_emr-etl-runner/ruby/1.9.1/gems/contracts-0.4/lib/contracts.rb:230:in `call_with'
    /home/ec2-user/snowplow/shared/bundle_emr-etl-runner/ruby/1.9.1/gems/contracts-0.4/lib/decorators.rb:157:in `run'
    /home/ec2-user/snowplow/releases/20150226101732/3-enrich/emr-etl-runner/lib/snowplow-emr-etl-runner/runner.rb:72:in `run_emr'
    /home/ec2-user/snowplow/releases/20150226101732/3-enrich/emr-etl-runner/lib/snowplow-emr-etl-runner/runner.rb:56:in `run'
    /home/ec2-user/snowplow/shared/bundle_emr-etl-runner/ruby/1.9.1/gems/contracts-0.4/lib/contracts.rb:230:in `call'
    /home/ec2-user/snowplow/shared/bundle_emr-etl-runner/ruby/1.9.1/gems/contracts-0.4/lib/contracts.rb:230:in `call_with'
    /home/ec2-user/snowplow/shared/bundle_emr-etl-runner/ruby/1.9.1/gems/contracts-0.4/lib/decorators.rb:157:in `run'
    /home/ec2-user/snowplow/current/3-enrich/emr-etl-runner/bin/snowplow-emr-etl-runner:39:in `<main>'
```

Retrying the job worked well, so it seems to be a transient AWS error.

**Comment by alexanderdean** [comment]
Thanks @danisola - have you seen this just on job submission or also during wait_for?

**Comment by danisola** [comment]
On job submission: https://github.com/snowplow/snowplow/blob/master/3-enrich%2Femr-etl-runner%2Flib%2Fsnowplow-emr-etl-runner%2Femr_job.rb#L288

**Comment by alexanderdean** [comment]
Closing as relevant parts have been pulled in. Thanks Dani!

**Pull request closed without merging**
