### PR TITLE
Hotfix 501 code error. https requered

### PR DESCRIPTION
**Pull request by kononenko-nikolay**
Hi folks, it just hotfix. my job's had crashed without that.

### CODE REVIEW

**Comment by snowplowcla** [comment]
Thanks for your pull request. Is this your first contribution to a Snowplow open source project? Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).

:memo: Please visit https://github.com/snowplow/snowplow/wiki/CLA to learn more and sign.

Once you've signed, please reply here (e.g. I signed it!) and we'll verify. Thanks.

**Comment by chuwy** [comment]
Thanks @kononenko-nikolay. We rolled out a hotfix for AMI5, bypassing the CI/CD. It should work now. Let us know if it doesn't.

**Comment by adamweyant** [comment]
> Thanks @kononenko-nikolay. We rolled out a hotfix for AMI5, bypassing the CI/CD. It should work now. Let us know if it doesn't.

Can you please hotfix/bypass CI for `s3://snowplow-hosted-assets/common/emr/snowplow-ami4-bootstrap-0.1.0.sh` as well?

**Comment by sharmaneelam** [comment]
@chuwy Could you please rollout fix for AMI4 too? We could see AMI5 bootstrap script has changed and AMI4 still has Http. Thanks for understanding as this is impacting our production system

**Comment by mra-github** [comment]
Would also like to request this be rolled out to AMI4 as our production system is being impacted.  Thanks!

**Comment by goodits** [comment]
On behalf of @chuwy, the AMI4 fix should be rolled out now too. Please confirm!

**Comment by mra-github** [comment]
Awesome, thanks @goodits !  Everything looks good now.  Really appreciate the quick turnaround!

**Comment by goodits** [comment]
No problem @mra-github. Thank you for confirming, and apologies for the inconvenience.

**Comment by kononenko-nikolay** [comment]
> it would be great if you can sign the CLA.

I did it. I glad being part of the project

**Comment by snowplowcla** [comment]
Confirmed! @kononenko-nikolay has signed the Contributor License Agreement. Thanks so much.

**Comment by benjben** [comment]
Thanks for the contribution @kononenko-nikolay !

**Pull request merged**
