### PR TITLE
Config: switch enabled to false in currency_conversion_config.json

### LINKED ISSUE #2327: Config: switch enabled to false in currency_conversion_config.json
Otherwise people are running Snowplow with all enrichments in that folder and all transaction-related events are failing due to missing API key.

### PR DESCRIPTION
**Pull request by dukex**
This commit closes #2327

### CODE REVIEW

**Comment by alexanderdean** [comment]
Thanks! Can you sign our CLA please: https://github.com/snowplow/snowplow/wiki/CLA

**Comment by dukex** [comment]
@alexanderdean done!

**Comment by alexanderdean** [comment]
Confirmed! Thanks so much

**Comment by dukex** [comment]
@alexanderdean I saw the tests is falling on openjdk, how to fix it?

**Comment by chuwy** [comment]
Closing in favor of: https://github.com/snowplow/snowplow/issues/2327

**Pull request closed without merging**
