### PR TITLE
Headers enrichment

### PR DESCRIPTION
**Pull request by khalidjaz**
Implementing https://github.com/snowplow/snowplow/issues/1373

iglu PR https://github.com/snowplow/iglu-central/pull/290

### CODE REVIEW

**Comment by alexanderdean** [comment]
Exciting! Have you signed the CLA? https://github.com/snowplow/snowplow/wiki/CLA

**Comment by khalidjaz** [comment]
Fixed your comment, I just signed it :)

**Comment by alexanderdean** [comment]
Confirmed - thanks so much! Assigning to @chuwy to review...

**Comment by chuwy** [comment]
@khalidjaz just remove please unused import (BasicHeaderValueParser), format config file in according with other enrichments (cookie extractor config has different formatting) and squash commits into one. Everything else looks good. Thank you!

**Comment by khalidjaz** [comment]
Done thank you so much @chuwy and @alexanderdean!

**Comment by chuwy** [comment]
Closing in favor of: https://github.com/snowplow/snowplow/issues/1373

**Pull request closed without merging**
