### PR TITLE
Fixes #3085 - EmrEtlRunner : misnamed CloudFront-like conversion

### LINKED ISSUE #3085: EmrEtlRunner: race condition overwriting files during staging step
Some raw files are misnamed during the [CloudFront-like conversion process](https://github.com/snowplow/snowplow/blob/master/3-enrich/emr-etl-runner/lib/snowplow-emr-etl-runner/s3_tasks.rb#L80), causing 2 root problems of missing files.

In the example below the time-stamp into the filename of both files is always renamed as 2017-01-13-03 (UTC). A 2017-01-13-04 file is missing.

EmrEtlRunner output:
```
[Fri Jan 13 06:15:05 UTC 2017] (t3)    MOVE snowplow-collectors-log/e-xrnips2p/i-050292a49/_var_log_tomcat8_rotated_localhost_access_log.txt1484280061.gz -> viadeo-snowplow-processing/processing/var_log_tomcat8_rotated_localhost_access_log.2017-01-13-03.us-east-1.i-050292a49944536d7.txt.gz
[Fri Jan 13 06:15:05 UTC 2017] (t5)    MOVE snowplow-collectors-log/e-xrnips2p/i-050292a49/_var_log_tomcat8_rotated_localhost_access_log.txt1484276462.gz -> viadeo-snowplow-processing/processing/var_log_tomcat8_rotated_localhost_access_log.2017-01-13-03.us-east-1.i-050292a49944536d7.txt.gz
```

Time-stamp conversion should be : 
- 1484280061 = 13/1/2017 at 5:01:01 CET
- 1484276462 = 13/1/2017 at 4:01:02 CET

So, when the file is archived the "2017-01-13-0**3**" could be either the one at 5:01 or the one at 4:01 without any file named as "2017-01-13-0**4**"

______ 
**Additional info :** 
- We have more than 30,000 files in our raw/in bucket ( remaining Elastic Beanstalk logs)
- I wasn't able to verify if the issue comes from ruby or jruby ([suspect bug](https://github.com/jruby/jruby/issues/3670) in jruby)
Maybe the [bump to 9.1.6.0 ](https://github.com/snowplow/snowplow/pull/3029/commits/70c9bc1dba4a9be01dcb086a9881a768deb527eb) could fix the issue but I wasn't able to make run the snowplow-emr-etl-runner & snowplow-storage-loader with this version.
- We have this issue at least once every two days

**Bonus :** 
Maybe keeping the timestamp in the filename could be interesting to validate the converted CloudFront format.

**Related**:
- [61 Pygmy Parrot](https://github.com/snowplow/snowplow/milestone/64?closed=1)
  - #1398 - EmrEtlRunner: change Clojure Collector log timestamp format to match CloudFront logs ( https://github.com/snowplow/snowplow/commit/4b36d14868340821b8665d326376383faf0f41ab) 
  - #1379 - EmrEtlRunner: append region name to Clojure Collector log files
  - #1404 - EmrEtlRunner: append rather than prepend instance names to Clojure Collector log files

### PR DESCRIPTION
**Pull request by vceron**
The converted datetime doesnt match every time with the original timestamp.
A "reverse conversion" is done afterwards.

It iterates some times on the same filename/timestamps and send the file to a retry folder if the conversion continues to fail.

The rejected file is processed in the next run.
 
Fixes #3085

[s3_tasks_spec.rb](https://github.com/snowplow/snowplow/blob/master/3-enrich/emr-etl-runner/spec/snowplow-emr-etl-runner/s3_tasks_spec.rb) passes :ok_hand:

### CODE REVIEW

**Comment by snowplowcla** [comment]
Thanks for your pull request. Is this your first contribution to a Snowplow open source project? Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).

:memo: **Please visit https://github.com/snowplow/snowplow/wiki/CLA to learn more and sign.**

Once you've signed, please reply here (e.g. `I signed it!`) and we'll verify. Thanks.

**Comment by vceron** [comment]
I signed it!

**Comment by snowplowcla** [comment]
Confirmed! @vceron has signed the Software Grant and Corporate Contributor License Agreement. Thanks so much

**Comment by BenFradet** [comment]
@vceron 

Unfortunately, we've moved to S3DistCp for staging and we're not doing any renaming anymore.

Thanks a lot for your contribution anyway!

**Comment by vceron** [comment]
So they will not have this format any more @BenFradet  ?
var_log_tomcat8_rotated_localhost_access_log.**2017-08-10-19**.us-east-1.i-06e3148.txt.gz

**Comment by BenFradet** [comment]
no indeed, the filenames and the folder structure will be kept as is

**Comment by vceron** [comment]
OK
Do you have a command/script to identify missing raw files instead ?
https://gist.github.com/vceron/014dd82cec201862dc8da1020cbd9a3f#file-monitor-snowplow-raw-files-from-collector-L13

**Comment by BenFradet** [comment]
You can work with the unix timestamp in the filename e.g. `_var_log_tomcat8_rotated_localhost_access_log.txt1502161261.gz`

**Pull request closed without merging**
