### PR TITLE
Change compression on some columns to AZ64. Closes #4219.

### LINKED ISSUE #4219: Redshift: Convert atomic.events to use AZ64 where possible
We've noticed some significant performance improvements when using AZ64 compression (particularly on timestamps).

The difference in terms of disk space is minimal (-2% to 2%) we've found but the performance increase warrants making the change from ZSTD to AZ64.

### PR DESCRIPTION
**Pull request by miike**
New version of atomic.events with AZ64 compression.

### CODE REVIEW

**Comment by alexanderdean** [comment]
@paulboocock we need to decide where to home the Redshift table definition...

**Comment by paulboocock** [comment]
We could make `snowplow/redshift-storage` and move https://github.com/snowplow/snowplow/tree/master/4-storage/redshift-storage 

Open to a better name for that repo though @alexanderdean

**Comment by alexanderdean** [comment]
Maybe we move it into the RDB Loader repo? /cc @chuwy

**Comment by chuwy** [comment]
> Maybe we move it into the RDB Loader repo?

I think it's a good idea. Snowflake Loader already has it and we can be consistent across all Loader/Storages.

**Comment by chuwy** [comment]
Created few tickets: https://github.com/snowplow/snowplow-rdb-loader/issues/412, https://github.com/snowplow-incubator/snowplow-bigquery-loader/issues/181, https://github.com/snowplow/snowplow-elasticsearch-loader/issues/176

**Comment by miike** [comment]
Closing as the issues have been separated out into separate issues.

**Pull request closed without merging**
