### PR TITLE
env-encrich-conf: use envs  for emr config

### PR DESCRIPTION
**Pull request by danwald**
This PR uses ENV values for the config of the emr-etl-runner.
Previous defaults are used where appropriate (leaving blank/nil where they should be). 
It makes it much each to configure when using docker containers.

### CODE REVIEW

**Comment by alexanderdean** [comment]
Thanks! Have you signed our CLA? https://github.com/snowplow/snowplow/wiki/CLA

**Comment by danwald** [comment]
just did

**Comment by alexanderdean** [comment]
Confirmed! Thanks so much

**Comment by dukex** [comment]
Hi @danwald, 
Can you please rebase your branch with master to @alexanderdean accept it?

**Comment by danwald** [comment]
Updated Duke...
Cheers,
- danny

**Comment by dukex** [comment]
@alexanderdean Do you see any trouble in this pull request?

**Comment by BenFradet** [comment]
We're now moving away from emr etl runner to [Dataflow Runner](https://github.com/snowplow/dataflow-runner) so this PR doesn't make a lot of sense anymore, sorry for the lack of follow-up, closing.

**Pull request closed without merging**
