### PR TITLE
Common: redirect support request to discourse in CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by ksnabb**
Support request should be sent to Discourse. Based on the knowledge gained from the google group post here:

https://groups.google.com/d/msg/snowplow-user/XGeayqKxvp8/Ryxu-ASzAQAJ

### CODE REVIEW

**Comment by chuwy** [comment]
I would actually also change "SnowPlow" to "Snowplow"

**Comment by ksnabb** [comment]
all done

**Comment by BenFradet** [comment]
Nice, scheduling.

**Comment by snowplowcla** [comment]
Confirmed! @ksnabb has signed the Individual Contributor License Agreement. Thanks so much

**Pull request closed without merging**
