### PR TITLE
Common: update README markdown according to CommonMark spec

### LINKED ISSUE #3157: Common: update READMEs markdown in according with CommonMark
Links and images are broken. To fix them spaces between content and anchor should be removed

### PR DESCRIPTION
**Pull request by zcei**
Hej,

after I read a lot through Wiki & README, I figured that this is not how it should look like and found the related ticket.
As I have no access to Wiki I cannot help out there, but hope this is a good start

Fixes #3157

### CODE REVIEW

**Comment by snowplowcla** [comment]
Thanks for your pull request. Is this your first contribution to a Snowplow open source project? Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).

📝 Please visit https://github.com/snowplow/snowplow/wiki/CLA to learn more and sign.

Once you've signed, please reply here (e.g. I signed it!) and we'll verify. Thanks.

**Comment by zcei** [comment]
Done ✅

**Comment by snowplowcla** [comment]
Confirmed! @zcei has signed the Individual Contributor License Agreement. Thanks so much

**Comment by alexanderdean** [comment]
Thanks so much Stephan, assigning into R88...

**Comment by zcei** [comment]
Shall I change the PR base to `release/r88-angkor-wat` then?

**Comment by alexanderdean** [comment]
No it's okay thanks, @chuwy will handle it!

**Comment by chuwy** [comment]
Cherry-picked into https://github.com/snowplow/snowplow/pull/3133. Thanks @zcei!

**Pull request closed without merging**
