### PR TITLE
Scala Common Enrich: use only base MIME type in content-type check for SendGrid Adapter

### PR DESCRIPTION
**Pull request by ninjabear**
fix for #2328

### CODE REVIEW

**Comment by alexanderdean** [comment]
Scheduling into R77 and assigning to @fblundun to review...

**Comment by fblundun** [comment]
Looks good to me!

**Comment by ninjabear** [comment]
I've verified both the existing problem and that this PR fixes it now. One to watch out for is that the "test your integration" button sends the application/json content type and the regular API sends the extended version with the charset.

**Comment by alexanderdean** [comment]
Many thanks @ninjabear ! Will get this fix merged in...

**Comment by alexanderdean** [comment]
Tweaked title

**Comment by alexanderdean** [comment]
Closing as merging into release branch now

**Pull request closed without merging**
