### PR TITLE
Added initial Spark data modeling framework

### PR DESCRIPTION
**Pull request by alexanderdean**
@yalisassoon, @bogaert - this is a PR for an initial (functional) data modeling framework using Spark.

It is designed to work with the most recent version of the Snowplow enriched event format. As a placeholder for some serious data modeling, the initial version simply counts the number of events by geo_city.

Snowplow enriched events are converted into the exact same JSON format as that used to load into Elasticsearch, prior to analysis.

You can run the fat jar on Elastic MapReduce using the `inv run_emr` function. Check `tasks.py` for other helper functions.

For more background, see this weekend's release of the new spark-example-project: https://github.com/snowplow/spark-example-project

### CODE REVIEW

**Comment by snowplowcla** [comment]
@dilyand @bogaert can we close this? Presumably there's nothing here needed for the Spark web data model.

**Comment by alexanderdean** [comment]
@bogaert @dilyand can we close this? Presumably there's nothing here we need in the Spark web data model.

**Comment by bogaert** [comment]
@alexanderdean Yep, this can be closed.

**Comment by alexanderdean** [comment]
Thanks, closing

**Pull request closed without merging**
