### PR TITLE
Common: rename Caravel to Superset

### PR DESCRIPTION
**Pull request by thalesmello**
The Caravel project has been renamed to [Superset](https://github.com/apache/incubator-superset)

### CODE REVIEW

**Comment by snowplowcla** [comment]
Thanks for your pull request. Is this your first contribution to a Snowplow open source project? Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).

📝 Please visit https://github.com/snowplow/snowplow/wiki/CLA to learn more and sign.

Once you've signed, please reply here (e.g. I signed it!) and we'll verify. Thanks.

**Comment by thalesmello** [comment]
I signed it

**Comment by snowplowcla** [comment]
Confirmed! @thalesmello has signed the Individual Contributor License Agreement, thanks so much

**Comment by chuwy** [comment]
Whoops! Missed the PR. Pushing back to R103.

**Pull request closed without merging**
