### PR TITLE
Feature/bigquery storage loader

### PR DESCRIPTION
**Pull request by RajeshHegde**
We at BigDecisions.Com have developed storage loader for BigQuery by flattening the unstruct_events. Enriched events will be split into daily table to make cost optimised while querying. This PR addresses the following issue  #2732 . Please feel free the add comments and required changes to accept this PR. We would love to contribute.

### CODE REVIEW

**Comment by alexanderdean** [comment]
Hey @RajeshHegde - this is very exciting! A few comments:

* Could you start fleshing out some documentation somewhere in the PR?
* Am I right in thinking you are downloading all of the events to the machine running StorageLoader - like Postgres loading, that's a singleton process rather than the distributed load processes we prefer. What kinds of volumes have you tested this with?
* It looks like you have some new options for the target in config.yml - again could you document what they are?
* Am I right in thinking that you didn't add support for custom or derived contexts - just unstructured events?
* It looks like the flattening of unstructured events would depend on the BigQuery table having been pre-prepared with slots for the given unstructured events, and the schema for that BigQuery table would have to have been pre-supplied in the config.yml schema field. Is that right? Does the load fail if a new event type is found in the data which hasn't been pre-added to the table and schema? What's your internal process for supporting this?

Phew! Those are my initial questions - apologies for so many Qs, it's just very exciting to be starting a dialog with a production user of BigQuery with Snowplow!

**Comment by RajeshHegde** [comment]
### BigQuery storage loader
#### Introduction
BigQuery is Google's fully managed, petabyte scale, low cost analytics data warehouse. BigQuery is serverless, there is no infrastructure to manage and you don't need a database administrator, so you can focus on analyzing data to find meaningful insights, use familiar SQL, and take advantage of pay-as-you-go model.

#### Setup BigQuery

- Install BigQuery CLI - [https://cloud.google.com/sdk/docs/quickstart-debian-ubuntu](https://cloud.google.com/sdk/docs/quickstart-debian-ubuntu)
- Create a project in Google Console
- Make sure you have access right to create BigQuery dataset and upload data

#### Configuration
You can add BigQuery as one of the storage targets.
```

- name: "Name of the project"
  type: bigquery
  schema: /path/to/json/schema/file
  dataset: "Name of dataset"
  table_prefix: "Prefix to date partitioned table"
  maxerror: 1000 # Stop loading on first error, or increase to permit more load errors
  replace: false
  timezone: "Timezone"
  processing_dir: /path/to/tmp/directory/for/processing

```

New config options:
`schema`:  BigQuery require a JSON schema which describes the structure of the table. 

**Note:  Currently we use a python script to generate schema from iglu schema files. We can write it in ruby so that it will be easy to follow.


`dataset`:  Dataset is similar to database which can have collection of tables.

`table_prefix`: Currently we are partitioning the data into date based tables. Since Google charges based on the amount of data it queried, by partitioning the data makes more cost optimised. But BigQuery have a limitation of number of table can be queried at a time, we are combining to form a monthly table at the end of the month. If the tables are partitioned by date then BigQuery have functions to query across multiple tables be date range.

`replace`:  Loading the new data will erase the old entries if set true, else append

`timezone`:  Timezone by which data needs to be split into date table. Collector timestamp will be in UTC, timezone will be used to split the data into local timezone date.

`processing_dir`:  Temporary directory to process enriched events into date tables. 



**Note: this is temp documentation, will keep refining and updating.

**Comment by alexanderdean** [comment]
Thanks for this @RajeshHegde ! I don't think there's a specific need to rewrite your Python schema script in Ruby - ultimately this capability would move into Iglu (Scala) for us anyway, so limited gain in porting over right now... Looking forward to seeing it though!

**Comment by RajeshHegde** [comment]
We have integrated BigQuery with one of the earlier version of snowplow. Now we tried to upgrade to latest version and we are stuck in building the executable. It throws the following error, 
```
LoadError: no such file to load -- pg
  require at org/jruby/RubyKernel.java:944
  require at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:55
    <top> at uri:classloader:/storage-loader/lib/snowplow-storage-loader/bigquery_loader.rb:1
  require at org/jruby/RubyKernel.java:944
  require at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:55
   (root) at uri:classloader:/jruby/kernel/kernel.rb:1
    <top> at uri:classloader:/jruby/kernel/kernel.rb:13
  require at org/jruby/RubyKernel.java:944
   (root) at uri:classloader:/storage-loader/lib/snowplow-storage-loader.rb:27
    <top> at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:1
     load at org/jruby/RubyKernel.java:962
    <top> at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:55
  require at org/jruby/RubyKernel.java:944
   (root) at uri:classloader:/storage-loader/bin/snowplow-storage-loader:20
    <top> at uri:classloader:/META-INF/main.rb:1
ERROR: org.jruby.embed.EvalFailedException: (LoadError) no such file to load -- pg
```


Note: Im using vagrant on Mac and ran build.sh. Tried changing Jruby version also.

**Comment by alexanderdean** [comment]
We've been building recently on Mac through Vagrant and it's been working fine... Can you provide steps to reproduce from a fresh Vagrant? I'll then walk through them myself.

**Comment by RajeshHegde** [comment]
Steps to reproduce:

- Pull snowplow/snowplow master
- `vagrant up`
- `vagrant ssh`
- `cd 4-storage/storage-loader`
- `./build.sh`

It will throw the following error
`Your Ruby version is 2.2.3, but your Gemfile specified 1.9.3`

Now change the JRuby version in `build.sh`
```

rvm install jruby-1.7.23
bash -l -c 'rvm use jruby-1.7.23'

```
Run `./build.sh` again,
`vagrant@snowplow:/vagrant/4-storage/storage-loader$ ./deploy/snowplow-storage-loader`
 it will throw following error
```
LoadError: no such file to load -- pg
  require at org/jruby/RubyKernel.java:944
  require at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:55
    <top> at uri:classloader:/storage-loader/lib/snowplow-storage-loader/bigquery_loader.rb:1
  require at org/jruby/RubyKernel.java:944
  require at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:55
   (root) at uri:classloader:/jruby/kernel/kernel.rb:1
    <top> at uri:classloader:/jruby/kernel/kernel.rb:13
  require at org/jruby/RubyKernel.java:944
   (root) at uri:classloader:/storage-loader/lib/snowplow-storage-loader.rb:27
    <top> at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:1
     load at org/jruby/RubyKernel.java:962
    <top> at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:55
  require at org/jruby/RubyKernel.java:944
   (root) at uri:classloader:/storage-loader/bin/snowplow-storage-loader:20
    <top> at uri:classloader:/META-INF/main.rb:1
ERROR: org.jruby.embed.EvalFailedException: (LoadError) no such file to load -- pg
```

**Comment by alexanderdean** [comment]
Okay thanks for that @RajeshHegde , I will take a look...

**Comment by RajeshHegde** [comment]
Thanks @alexanderdean

**Comment by RajeshHegde** [comment]
There was a problem in my bigquery_loader script. Now I'm able to build the executable. Thanks @alexanderdean

**Comment by alexanderdean** [comment]
Ah! Thanks for the update @RajeshHegde

**Comment by RajeshHegde** [comment]
@alexanderdean  I have added schema generator script at `4-storage/storage-loader/lib/snowplow-storage-loader/schema_generator.py`, please suggest if script need to be kept in any specific path.


#### Usage

```
cd 4-storage/storage-loader/lib/snowplow-storage-loader/
python schema_generator.py --iglu '/path/to/iglu/schemas/directory' > schema.json
```

Options:
`-i` or `--iglu` :  Path to the parent directory of all iglu schemas,

**Comment by alexanderdean** [comment]
Many thanks for sharing! Will take a look.

**Comment by RajeshHegde** [comment]
@alexanderdean Currently we don't use custom or derived contexts so these scripts support only unstructured events. If you can tell me how to handle contexts we can think of including it in the PR.

**Comment by RajeshHegde** [comment]
Hi @alexanderdean,
Its been long time since PR is pending, can you please give an update on this, anything we need to do to merge this PR?

**Comment by alexanderdean** [comment]
Hi @RajeshHegde - you are right, this PR has been around for a long time.

In terms of an update from our side:

* We are planning a major refactor of the `atomic.events` table - expect an RFC on this in due course
* We have started work on a version of Snowplow targeting Google Cloud Platform, including eventually BigQuery - expect an RFC on this in due course
* We are sketching out some innovative ideas for how best to represent Snowplow enriched events in BigQuery

**Given the above, your PR is not on a fast-track to merging.** However, it does contain some really helpful code, and we'd certainly like to keep this PR open to feed back into the above action items.

Thanks again for your contribution.

**Comment by RajeshHegde** [comment]
Thanks for the update @alexanderdean.

**Comment by alexanderdean** [comment]
Many thanks for this @RajeshHegde - it was much appreciated. I am closing this PR now because the current situation is quite different from the time at which you submitted this PR:

1. The Ruby StorageLoader has been retired, replaced with the Snowplow Relational Database Loader (RDB Loader), written in Scala
2. @chuwy is starting work on a new Snowplow BigQuery Loader, which you can follow in this repo: https://github.com/snowplow-incubator/snowplow-bigquery-loader

So I am closing this PR - but thanks again for the original submission. It's really appreciated and I hope this closing doesn't deter you from submitting pull requests to Snowplow in the future.

👍

**Pull request closed without merging**
