### PR TITLE
fixed hocon sample file for scala-stream-collector

### PR DESCRIPTION
**Pull request by simplesteph**
I'll be working on Snowplow a bit soon, so expect quite a few PRs, especially on the Kafka side :)
This one is about making the hocon valid for scala-stream-collector

### CODE REVIEW

**Comment by snowplowcla** [comment]
Thanks for your pull request. Is this your first contribution to a Snowplow open source project? Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).

📝 Please visit https://github.com/snowplow/snowplow/wiki/CLA to learn more and sign.

Once you've signed, please reply here (e.g. I signed it!) and we'll verify. Thanks.

**Comment by simplesteph** [comment]
I signed it!

**Comment by simplesteph** [comment]
closing in favour of https://github.com/snowplow/snowplow/pull/3189

**Comment by alexanderdean** [comment]
Confirmed! @simplesteph has signed the Individual Contributor License Agreement. Thanks so much

**Comment by snowplowcla** [comment]
Confirmed! @simplesteph has signed the Individual Contributor License Agreement. Thanks so much

**Pull request closed without merging**
