### PR TITLE
Update build.sbt

### PR DESCRIPTION
**Pull request by piyushknoldus**
scala-stream-collector: added docker plugin for stdout module. This now will go with the documentation - https://github.com/snowplow/snowplow/wiki/Run-the-Scala-Stream-Collector to run the jar using stdout as the target.

### CODE REVIEW

**Comment by tgampiyush** [comment]
what the next step for this @chuwy @dilyand . I think the build got failed, so is there any way to re-trigger this build

**Comment by chuwy** [comment]
Restarted manually.

**Comment by tgampiyush** [comment]
hi @chuwy it got failed again, I am not trying to get why.
 can you please help.

**Comment by tgampiyush** [comment]
Hi @chuwy sorry to disturb you again, but the build is not passing. can you please help in this.

**Comment by tgampiyush** [comment]
Hi @chuwy , request you to please look into this why the build is not clearing.

**Comment by benjben** [comment]
Thanks for the contribution @piyushknoldus !

**Pull request merged**
