### PR TITLE
Improve scala collector

### PR DESCRIPTION
**Pull request by ferrlin**
The first plan is to format code so I added scalariform support for this project. The preferences for the formatter can be found in BuildSettings.scala under project folder.

I also added scalastyle to check code conventions but I didn't attempted to fix those warnings yet. That will follow after this pull.

Cheers,

### CODE REVIEW

**Comment by alexanderdean** [comment]
Hey! Interesting idea. A few notes:

* Editor-specific ignores should be put in your global .gitignore, not in project-specific ones
* Replacing ASCII operators (=>) with unicode ones (⇒) is something we'll never do at Snowplow, sorry
* There is already a PR to bump the Scala version - this is a few releases off - https://github.com/snowplow/snowplow/pull/1381

Cheers!

**Comment by ferrlin** [comment]
Refactoring highlights:

- applied best practice to defining actors
-- props should be defined inside the companion object of the actor
- code duplication on routes handled through directive composition technique
- route composition
- CollectorService as trait to be mixin to CollectorHandler (previously called CollectorServiceActor)

**Comment by alexanderdean** [comment]
Cool! Have you signed our CLA? https://github.com/snowplow/snowplow/wiki/CLA

**Comment by ferrlin** [comment]
I've already signed the ICLA.

Recent commit updates:
- No test to confirm fix on cyclomatic complexity for createKinesisClient. Please review the code.
- Two scalastyle warnings left which are,
snowplow.collectors.scalastream/ResponseHandler.scala:66:6: Method is longer than 50 lines
snowplow.collectors.scalastream/sinks/StdoutSink.scala:43:4: Regular expression matched 'println'

**Comment by alexanderdean** [comment]
Confirmed CLA signed! Thanks John. Assigning to Fred...

**Comment by ferrlin** [comment]
Updates:

 rebase from recent release of snowplow
 * CollectorConfig as trait for mixin
 * refactorings to fix scalastyle warning

I'm thinking of adding some property based testing to traits with scalacheck. Is this something that snowplow would also consider?

**Comment by alexanderdean** [comment]
Hi @ferrlin - yes sure, we have ScalaCheck tests elsewhere in Snowplow, they are pretty cool...

**Comment by ferrlin** [comment]
Scalacheck testing
* CollectorConfig
* KinesisSink

I would like to know if it makes sense to test KinesisSink. When doing property testing, it tries to connect to Amazon to create the client.
```
[info] ! KinesisSink.check if stream exists: Exception raised on property evaluation.
[info] > Exception: com.amazonaws.AmazonClientException: Unable to load AWS credentials from the /AwsCredentials.properties file on the classpath
[info] ! KinesisSink.check raw event stored: Exception raised on property evaluation.
[info] > Exception: com.amazonaws.AmazonClientException: Unable to load AWS credentials from the /AwsCredentials.properties file on the classpath
```

I would like to know your thoughts on this to move forward.

Thanks,

**Comment by alexanderdean** [comment]
@ferrlin at some point we may embed encypted AWS credentials in the Travis file, but it's unlikely and in any case you wouldn't be able to use those credentials when testing locally. Hope this answers your question.

**Comment by ferrlin** [comment]
I'll try if I could mock this instead. Thanks.

**Comment by BenFradet** [comment]
@ferrlin 

Unfortunately, we've made some progress parallel to this in #3274.

Sorry for the lack of activity on our side and thanks a lot for your contribution anyway.

**Pull request closed without merging**
