### PR TITLE
Documentation: fix broken links in storage/postgres's README.md

### PR DESCRIPTION
**Pull request by premjg**
Fixes https://github.com/snowplow/snowplow/issues/3389

### CODE REVIEW

**Comment by snowplowcla** [comment]
Thanks for your pull request. Is this your first contribution to a Snowplow open source project? Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).

📝 Please visit https://github.com/snowplow/snowplow/wiki/CLA to learn more and sign.

Once you've signed, please reply here (e.g. I signed it!) and we'll verify. Thanks.

**Comment by premjg** [comment]
Signed it!

**Comment by snowplowcla** [comment]
Confirmed! @premjg has signed the Individual Contributor License Agreement. Thanks so much

**Comment by alexanderdean** [comment]
Fixed title

**Pull request closed without merging**
