### PR TITLE
Updated kinesis-elasticsearch-sink from Elasticsearch 1.4 to 2.3

### PR DESCRIPTION
**Pull request by KevinNZ83**
- Updated joda-time references
- Refactored Transport to support new elasticsearch API

### CODE REVIEW

**Comment by snowplowcla** [comment]
Thanks for your pull request. Is this your first contribution to a Snowplow open source project? Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).

:memo: **Please visit https://github.com/snowplow/snowplow/wiki/CLA to learn more and sign.**

Once you've signed, please reply here (e.g. `I signed it!`) and we'll verify. Thanks.

**Comment by KevinNZ83** [comment]
I signed it!

**Comment by snowplowcla** [comment]
Confirmed! @KevinNZ83 has signed the Individual Contributor License Agreement. Thanks so much.

**Comment by jbeemster** [comment]
Hi @KevinNZ83, I have cherry-picked the updates for the Transport client as part of this ticket:
* https://github.com/snowplow/snowplow/issues/2525

**Pull request closed without merging**
