### PR TITLE
Added Redshift DDL & JSON path for com.amazon.aws.lambda/s3_notification_event

### PR DESCRIPTION
**Pull request by ninjabear**

### CODE REVIEW

**Comment by alexanderdean** [comment]
Assigning to @chuwy to bring this into his release branch. Once this has been brought in, please de-schedule the PR from the milestone and close it...

**Comment by chuwy** [comment]
Done.

**Comment by chuwy** [comment]
Hey @ninjabear! Could you please reprocess `com.amazon.aws.lambda/s3_notification_event/jsonschema/1-0-0` with latest Schema Guru? There was a [critical bug](https://github.com/snowplow/schema-ddl/issues/50) in `schema-ddl` 0.3.0 which I guess [affected](https://github.com/snowplow/snowplow/pull/2591/commits/661c6a60c84b3a8af113118d162f0a29680d6904#diff-556640bbf51548b34c1f11b557e60001R31) these DDLs.

**Comment by ninjabear** [comment]
Hey @chuwy I have patched this, also I removed the max-size restriction which was in error. Does it look right now?

see also https://github.com/snowplow/iglu-central/pull/354 for the updated json schema

**Comment by chuwy** [comment]
Hey @ninjabear! Thanks, looks good to me.
Cherry-picking it into r82.

**Pull request closed without merging**
