### PR TITLE
Feature/cloudfront access log adapter

### PR DESCRIPTION
**Pull request by fblundun**

### CODE REVIEW

**Comment by fblundun** [comment]
Closing because there are a couple of fields I need to convert from string to number...

**Comment by fblundun** [comment]
Reopening now that the generated JSON matches the schema.

**Comment by alexanderdean** [comment]
I don't think this can be reopened...

**Comment by alexanderdean** [comment]
Nice! Is there a JSON Path file in there somewhere too...

**Comment by fblundun** [comment]
Just assigned myself, I'll write it now...

**Pull request closed without merging**
