### PR TITLE
EmrEtlRunner: add support for custom bootstrap actions

### PR DESCRIPTION
**Pull request by danisola**
This PR allows to add a EMR custom bootstrap action.

### CODE REVIEW

**Comment by alexanderdean** [comment]
Hey @danisola! Thanks for this, it looks great. Question: should this be an array rather than a singular one?

**Comment by danisola** [comment]
Yes, having multiple actions would make it more general. I'll try to get some more time to do it.

**Comment by alexanderdean** [comment]
Thanks @danisola !

**Comment by alexanderdean** [comment]
Bringing forwards...

**Comment by alexanderdean** [comment]
Merged, closing! Thanks so much.

**Pull request closed without merging**
