### PR TITLE
Redshift: widen se_label to 4,096 to support URLs etc

### LINKED ISSUE #3541: Scala Common Enrich: remove unused version member in Enrichment trait
It looks like DefaultArtifactVersion in Enrichment is not used anywhere.

### PR DESCRIPTION
**Pull request by knservis**

### CODE REVIEW

**Comment by alexanderdean** [comment]
Switched reviewer to Ben

**Comment by knservis** [comment]
@BenFradet I am not sure what is happening with history (have merged master to both the release and the issue branches..)

**Comment by alexanderdean** [comment]
Looks like your rebase has gone wrong

**Comment by knservis** [comment]
@BenFradet eventually they will end up in the same PR to master, but it is more clear to consider them in isolation initially.

**Comment by BenFradet** [comment]
problem is that there is a lot of overlap between the two prs and that slows down review.

**Comment by knservis** [comment]
@BenFradet The merged changes are now in the release branch. We'll look at them in the final PR

**Pull request merged**
