### PR TITLE
Scala Common Enrich: bump mandrill event versions to 1-0-1

### PR DESCRIPTION
**Pull request by acgray**
See https://github.com/snowplow/iglu-central/pull/628

### CODE REVIEW

**Comment by snowplowcla** [comment]
@acgray has signed the Software Grant and Corporate Contributor License Agreement

**Comment by BenFradet** [comment]
Could we add this and snowplow/iglu-central#628 to Knossos ? @alexanderdean @knservis

**Comment by alexanderdean** [comment]
No, Knossos has been kicked off already. Per the off-site, we are trying not to add tickets to sprints that have already started.

**Comment by BenFradet** [comment]
Yup, that's my bad I wasn't aggressive enough in scheduling, scheduling now.

**Comment by BenFradet** [comment]
mmmh I thought those would in 102...

**Comment by BenFradet** [comment]
Hey @acgray ,

Apparently we have customers running the Mandrill integration without running into issues with this new subaccount property.

Because updating the jsonpaths associated with the 1-0-1 schemas would fail their data loading into redshift if we don't update their tables, we're postponing this feature.

The commit now lives in #3716, closing.

**Comment by alexanderdean** [comment]
I don't think this is blocked - we can emit the newer schemas, they will pass validation, we simply will be loading the older versions (1-0-0s) into Redshift.

**Comment by BenFradet** [comment]
true...reopening

**Pull request closed without merging**
