### PR TITLE
Scala Common Enrich: remove unused version member in Enrichment trait

### PR DESCRIPTION
**Pull request by knservis**
- Second commit only removes trailing whitespace

### CODE REVIEW

**Comment by alexanderdean** [comment]
Why is there a separate whitespace commit?

**Comment by knservis** [comment]
@alexanderdean It would have been too hard to see the changes otherwise. I can squash them together now that we are done.

**Comment by dilyand** [comment]
@alexanderdean Was there anything you wanted me to do with this?

**Comment by alexanderdean** [comment]
Apologies, must have been butter-fingers

**Comment by knservis** [comment]
Already merged

**Pull request closed without merging**
