### PR TITLE
Automatically create duplicates.events table from atomic.events

### PR DESCRIPTION
**Pull request by sbonami**
To ease the automation of the setup of de-duplication, we can automatically generate the duplicates.events table from the atomic.events table's schema. To do so without loading any data, we simple provide an always false conditional.

### CODE REVIEW

**Comment by alexanderdean** [comment]
Thanks @sbonami - can you sign our CLA please: https://github.com/snowplow/snowplow/wiki/CLA

**Comment by sbonami** [comment]
@alexanderdean: Signed the Corporate Contributor one.

**Comment by alexanderdean** [comment]
Confirmed! Thanks so much

**Comment by alexanderdean** [comment]
Thanks for the contribution @sbonami - this is a won't fix now as we are prioritising our DynamoDB-based Spark deduplication.

**Pull request closed without merging**
